config/routes.rb
Rails.application.routes.draw do
  resources :socialmedia
  resources :category_directories
  resources :contacts
  resources :directories
  get 'dashboard/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'page#index'
  get 'dashboard' => "dashboard#index"
  get '/search' => "page#search", as: :search_path
  get '/dashboard/banner-homepage' => "dashboard#banner_homepage", as: :banner_homepage
  get '/dashboard/banner-category' => "dashboard#banner_category", as: :banner_category
  get '/dashboard/banner-article' => "dashboard#banner_article", as: :banner_article
  get 'backtosetup' => "dashboard#backtosetup"
  get 'backtosetup-event' => "dashboard#backtosetup_event"
  get 'open' => 'page#open', as: :open_article
  get 'contact-us'=> 'page#contact', as: :contact_us

  resources :users
  resources :videos
  resources :events
  resources :articles

  get 'index' => 'page#index', as: :index
  get 'event' => 'page#event', as: :page_event
  get 'all-category' => 'categories#index', as: :all_category
  get 'all-category-article' => 'categories#article', as: :all_category_article
  get 'all-category-event' => 'categories#event', as: :all_category_event
  get 'all-directory' => 'directories#index', as: :all_directory
  get 'semua-artikel' => 'page#latest', as: :latest
  get 'author' => 'page#author', as: :all_author

  resources :categories, path: ''

  devise_for :users,
  path:'admin',
  path_names:{sign_in: 'login',sign_out:'logout'}

  get 'author/:id', to: 'users#show', as: :author
  get ':category_name/:id', to: 'articles#show', as: :dtl_article

end

app/models/directory.rb
class Directory < ApplicationRecord

  belongs_to :category_directory

end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :set_directory, only: [:show, :edit, :update, :destroy]
  layout 'admin', except: 'show'
  before_action :authenticate_user!
  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.all
    if params[:name].present?
     @directories = Directory.where("name LIKE ?", "%#{params[:name]}%")
    end

  end

  # GET /directories/1
  # GET /directories/1.json
  def show
  end

  # GET /directories/new
  def new
    @directory = Directory.new
  end

  # GET /directories/1/edit
  def edit
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(directory_params)

    respond_to do |format|
      if @directory.save
        format.html { redirect_to directories_url, notice: 'Directory was successfully created.' }
        format.json { render :show, status: :created, location: @directory }
      else
        format.html { render :new }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directories/1
  # PATCH/PUT /directories/1.json
  def update
    respond_to do |format|
      if @directory.update(directory_params)
        format.html { redirect_to directories_url, notice: 'Directory was successfully updated.' }
        format.json { render :show, status: :ok, location: @directory }
      else
        format.html { render :edit }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory.destroy
    respond_to do |format|
      format.html { redirect_to directories_url, notice: 'Directory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directory
      @directory = Directory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directory_params
      params.require(:directory).permit(:name, :directory_type, :description, :address, :phonenumber, :province, :city, :instagram, :facebook, :twitter, :website, :map, :category_directory_id)
    end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/views/directories/_form.html.erb
<%= form_for @directory, :html => { :class => "form-horizontal directory", target: "_blank"  } do |f| %>

<% if @directory.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @directory.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">

        <div class="form-group">
          <%= f.label :name, :class => 'control-label' %>
          <%= f.text_field :name, :class => 'form-control' %>
          <%=f.error_span(:name) %>
        </div>
        <div class="form-group">
          <%= f.label :category_directory_id, :class => 'control-label' %>
          <%= f.select :category_directory_id, CategoryDirectory.all.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2 category-select",required: true %>
          <%=f.error_span(:category_id) %>
        </div>
        <div class="form-group">
          <%= f.label :description, :class => 'control-label' %>
          <%= f.text_area :description, :class => 'form-control' %>
          <%=f.error_span(:description) %>
        </div>
        <div class="form-group">
          <%= f.label :address, :class => 'control-label' %>
          <%= f.text_area :address, :class => 'form-control' %>
          <%=f.error_span(:address) %>
        </div>

        <div class="form-group">
          <%= f.label :map, :class => 'control-label' %>
          <%= f.text_area :map, :class => 'form-control' %>
          <%=f.error_span(:map) %>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :phonenumber, :class => 'control-label' %>
              <%= f.text_field :phonenumber, :class => 'form-control' %>
              <%=f.error_span(:phonenumber) %>
            </div>
          </div>


          <div class="col">
            <div class="form-group">
              <%= f.label :instagram, :class => 'control-label' %>
              <%= f.text_field :instagram, :class => 'form-control' %>
              <%=f.error_span(:instagram) %>
            </div>
          </div>

          <div class="col">
            <div class="form-group">
              <%= f.label :facebook, :class => 'control-label' %>
              <%= f.text_field :facebook, :class => 'form-control' %>
              <%=f.error_span(:facebook) %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :twitter, :class => 'control-label' %>
              <%= f.text_field :twitter, :class => 'form-control' %>
              <%=f.error_span(:twitter) %>
            </div>
          </div>


          <div class="col">
            <div class="form-group">
              <%= f.label :website, :class => 'control-label' %>
              <%= f.text_field :website, :class => 'form-control' %>
              <%=f.error_span(:website) %>
            </div>

          </div>

        </div>








        <div class="form-group">
          <div class="col-lg-offset-2 col-lg-10">
            <%= f.submit nil, :class => 'btn btn-primary' %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            directories_path, :class => 'btn btn-default' %>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>

<% end %>

app/views/directories/edit.html.erb
<%- model_class = Directory -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/directories/index.html.erb
<%- model_class = Directory -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_index_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")),new_directory_path,:class => 'btn btn-success mb-2', target:'_blank' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:directory_type) %></th>
                <th><%= model_class.human_attribute_name(:description) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @directories.each do |directory| %>
              <tr>
                <td><%= link_to directory.id, directory_path(directory) %></td>
                <td><%= directory.name %></td>
                <td><%= directory.directory_type %></td>
                <td><%= directory.description %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  directory_path(directory), :class => 'btn m-2 btn-default btn-xs', target: "blank" %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_directory_path(directory), :class => 'btn m-2 btn-default btn-xs', target:'_blank' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  directory_path(directory),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn m-2 btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
$(document).ready(function() {
  $('.table').DataTable();
} );
</script>

app/views/directories/new.html.erb
<%- model_class = Directory -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= articles_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/directories/show.html.erb
<%- model_class = Directory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @directory.name %></dd>
  <!-- <dt><strong><%= model_class.human_attribute_name(:directory_type) %>:</strong></dt>
  <dd><%= @directory.directory_type %></dd> -->
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @directory.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @directory.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phonenumber) %>:</strong></dt>
  <dd><%= @directory.phonenumber %></dd>
  <dt><strong><%= model_class.human_attribute_name(:province) %>:</strong></dt>
  <dd><%= @directory.province %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @directory.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:instagram) %>:</strong></dt>
  <dd><%= @directory.instagram %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook) %>:</strong></dt>
  <dd><%= @directory.facebook %></dd>
  <dt><strong><%= model_class.human_attribute_name(:twitter) %>:</strong></dt>
  <dd><%= @directory.twitter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @directory.website %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              directories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_directory_path(@directory), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              directory_path(@directory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>