config/routes.rb
Rails.application.routes.draw do
  resources :socialmedia
  resources :category_directories
  resources :contacts
  resources :directories
  get 'dashboard/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'page#index'
  get 'dashboard' => "dashboard#index"
  get '/search' => "page#search", as: :search_path
  get '/dashboard/banner-homepage' => "dashboard#banner_homepage", as: :banner_homepage
  get '/dashboard/banner-category' => "dashboard#banner_category", as: :banner_category
  get '/dashboard/banner-article' => "dashboard#banner_article", as: :banner_article
  get 'backtosetup' => "dashboard#backtosetup"
  get 'backtosetup-event' => "dashboard#backtosetup_event"
  get 'open' => 'page#open', as: :open_article
  get 'contact-us'=> 'page#contact', as: :contact_us

  resources :users
  resources :videos
  resources :events
  resources :articles

  get 'index' => 'page#index', as: :index
  get 'event' => 'page#event', as: :page_event
  get 'all-category' => 'categories#index', as: :all_category
  get 'all-category-article' => 'categories#article', as: :all_category_article
  get 'all-category-event' => 'categories#event', as: :all_category_event
  get 'all-directory' => 'directories#index', as: :all_directory
  get 'semua-artikel' => 'page#latest', as: :latest
  get 'author' => 'page#author', as: :all_author

  resources :categories, path: ''

  devise_for :users,
  path:'admin',
  path_names:{sign_in: 'login',sign_out:'logout'}

  get 'author/:id', to: 'users#show', as: :author
  get ':category_name/:id', to: 'articles#show', as: :dtl_article

end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  has_many :articles
  has_many :events
  has_many :social_media_authors, inverse_of: :user
  accepts_nested_attributes_for :social_media_authors, reject_if: :all_blank, allow_destroy: true
  mount_uploader :avatar, ImageUploader

  ROLES = {writer: "writer", admin:'admin'}

  scope :admin, -> {where(role: ROLES[:admin])}
  scope :writer, -> {where(role: ROLES[:writer])}

  def is_admin?
   self.role == ROLES[:admin]
 end

 def is_writer?
   self.role == ROLES[:writer]
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: 'show'
  layout 'admin', except: 'show'
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if request.fullpath.split("/")[1] != "author"
      redirect_to author_path(@user), status: 301
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if params[:editpass].present?
        if @user_with_password.update_with_password(user_params_password)
          format.html { redirect_to @user, notice: 'User Password was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @user_with_password = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :name, :role,:password, :password_confirmation, :fb, :ig, :yutube, :linkedin, :bio, :full_name,:avatar, social_media_authors_attributes:[:id, :user_id, :socialmedium_id, :account_username, :_destroy])
    end

    def user_params_password
      params.require(:user).permit(:current_password,:password,:password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <% if @article.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
</div>
<%= form_for @article, :html => { :class => "form-horizontal article", target: "_blank",onsubmit:"javascript: setTimeout(function(){location.replace('/backtosetup?id=#{@article.id}');}, 1500);return true;"   } do |f| %>
<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :title, :class => 'control-label' %>
          <%= f.text_field :title, :class => 'form-control', required: true %>
          <%=f.error_span(:title) %>
        </div>
        <div class="form-group">
          <%= f.label :metades, :class => 'control-label' %>
          <%= f.text_area :metades, :class => 'form-control',rows: 5, required: true %>
          <%=f.error_span(:metades) %>
        </div>
        <div class="form-group">
          <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {toolbar: 'mini'}%>
          <%=f.error_span(:content) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :image, "Thumbail Article", :class => 'control-label' %>
          <% if @article.image.nil? || @article.image.blank? %>
          <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250',required: true %>
          <% else %>
          <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @article.image.url %>
          <% end %>
          <%=f.error_span(:image) %>
        </div>

        <hr>
        <label for="">Category</label>
        <div class="form-group">
          <%= f.collection_select :title, Category.parent.where.not(slug:'event').order(:title), :title , :title, {}, {:class=>'parent_category w-100 form-control mb-2'} %>
          <%= f.grouped_collection_select :category_id, Category.parent.where.not(slug:'event').order(:title), :children, :title, :id , :title, {}, {:class=>'category-select w-100 form-control'} %>
          <%# f.label :category_id,"Set New Category", :class => 'control-label' %> <br>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Create New Category
          </button>
        </div>

        <hr>
        <div class="form-group">
          <%= f.label :category_id,"Set New Directory", :class => 'control-label' %> <br>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModaldirectory">
            Create New Directory
          </button>
        </div>
        <div class="form-group">
          <%= f.label :directory_id, :class => 'control-label' %>
          <%= f.select :directory_id, Directory.all.map {|s| [s.name, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2 directory-select"%>
          <%=f.error_span(:directory_id) %>
        </div>
        <hr>
        <div class="form-group">
          <label for="publish">Publish Date</label>
          <% if @article.new_record? %>
          <%= f.datetime_field :publish, :class => 'form-control ', required:true, value: DateTime.now.strftime("%Y-%m-%dT%H:%M") %>

          <% else %>
          <%= f.datetime_field :publish, :class => 'form-control', required:true, value: @article.publish.strftime("%Y-%m-%dT%H:%M") %>
          <% end %>
          <%=f.error_span(:publish) %>
        </div>
        <hr>
        <div class="form-group">
          <label for="">Tags</label>
          <%= f.text_field :tag_list, :class => 'hai', :value => @article.tag_list.join(",") %>
          <%=  @article.tag_list %>
        </div>
        <% if current_user.is_admin? %>
        <hr>
        <label for="">Writer</label>
        <div class="form-group">
          <% if @article.new_record?  %>
          <%= f.select :user_id, User.all.map {|s| [s.full_name, s.id ]},{:include_blank => '-Choose-', :selected => current_user.id }, :class=>"form-control w-100 select2 category-select",required: true %>
          <% else %>
          <%= f.select :user_id, User.all.map {|s| [s.full_name, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2 category-select",required: true %>
          <% end %>
        </div>
        <hr>
        <% else %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <% end %>



        <div class="form-group">
          <%= f.submit "Preview", :class => 'btn btn-outline-info prvs',onClick: "window.location.open().reload();" %>
          <%= f.submit "Draft", :class => 'btn btn-warning prvs',onClick: "window.location.open().reload();", name:"draft" %>
          <%= f.submit "Publish", :class => 'btn btn-success', name: "publish" %>
          <a data-confirm="Heads Up, Semua data yang di ubah tidak akan tersimpan! Apakah anda yakin?" class="btn btn-outline-danger" href="<%= articles_path %>">Cancel</a>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<script type="text/javascript">
  $('.mydatepicker').bootstrapMaterialDatePicker({ format: 'DD/MM/YYYY @HH:mm' });
  $("input[type='checkbox'], input[type='radio']").bootstrapSwitch();

  $('.hai').selectize({
    options:[
    <% @article.tag_list.each_with_index do |x, i|  %>
    {value:"<%= x %>", text:"<%= x %>"},
    <% end %>
    ],
    labelField: 'text',
    searchField: 'text',
    delimiter: ',',
    create: function(input) {
      return {
        value: input,
        text: input
      }
    }
  });
</script>


<script type="text/javascript">
  $(document).ready(
  function() {
    $('#new_category').on('ajax:success', function(data) {
      $('#new_category')[0].reset();
      $("body").click();
      $('#exampleModal').modal('hide')
      $(".category-select").select2({
        ajax: {
          url: "/all-category-article",
          dataType: 'json',
          type: "GET",
          delay: 250,
          data: function(params) {
            return { title: params.term }
          },
          processResults: function (data, params) {
            return {
              results: $.map(data, function(value, index){
                return {id: value.id, text: value.title};
              })
            };
          }

        },
        theme: "bootstrap",
        escapeMarkup: function (markup) { return markup; },

        placeholder: "Type to search",
      });
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(
  function() {
    $('#new_directory').on('ajax:success', function(data) {
      $('#new_directory')[0].reset();
      $("body").click();
      $('#exampleModaldirectory').modal('hide')
      $(".directory-select").select2({
        ajax: {
          url: "/all-directory.json",
          dataType: 'json',
          type: "GET",
          delay: 250,
          data: function(params) {
            return { name: params.term }
          },
          processResults: function (data, params) {
            return {
              results: $.map(data, function(value, index){
                return {id: value.id, text: value.name};
              })
            };
          }

        },
        theme: "bootstrap",
        escapeMarkup: function (markup) { return markup; },

        placeholder: "Type to search",
      });
    });
  });
</script>

<script type="text/javascript">

  $('.form-horizontal').onsubmit = function() {
    window.location.reload();

  }
</script>

<script type="text/javascript">
    var locations;
    var areas;
    $('.category-select').attr('required', 'required');
    $('.parent_category').attr('required', 'required');
    areas = $('.parent_category').html();
    locations = $('.category-select').html();

    $('.parent_category').change(function () {
      var region,
      escaped_region,
      options;
      region = $('.parent_category :selected').text();
      escaped_region = region.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
      options = $(locations).filter("optgroup[label=" + escaped_region + "]").html();
      if (options) {
        $('.category-select').html(options);
        return $('.category-select').removeAttr("disabled");

      } else {
        $('.category-select').empty();
        return $('.category-select').attr('required', 'required');
        return $('.parent_category').addClass("hide");

      }

    });
    </script>

app/views/users/_formedit.html.erb
<% if @user.errors.any? %>
<div class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
  <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= pluralize(@user.errors.count, "error") %> </h3>
  <p>prohibited this user from being saved:</p>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">

  <div class="col-md-8">
    <%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
    <div class="row">
      <div class="col-3">
        <div class="card">
          <div class="card-body">
            <div class="form-group">
              <%= f.label :avatar, :class => 'control-label' %>
              <% if @user.avatar.nil? || @user.avatar.blank? %>
                <%= f.file_field :avatar, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250' %>
              <% else %>
                <%= f.file_field :avatar, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @user.avatar.url %>
              <% end %>
              <%=f.error_span(:avatar) %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :username, :class => 'control-label' %> <small><i>Required</i></small>
                  <%= f.text_field :username, :class => 'form-control', required: true %>
                  <%=f.error_span(:username) %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%=  f.label :full_name, :class => 'control-label' %>
                  <%=  f.text_field :full_name, :class => 'form-control' %>
                  <%= f.error_span(:full_name) %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :email, :class => 'control-label' %> <small><i>Required</i></small>
                  <%= f.text_field :email, :class => 'form-control', required: true %>
                  <%=f.error_span(:email) %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :role, :class => 'control-label' %> <small><i>Required</i></small>
                  <%= f.select :role, User::ROLES.map {|r| [r.last.to_s, r.last.to_s] }, {:include_blank => '- Choose -'}, :class => 'form-control',:required => true %>
                  <%=f.error_span(:role) %>
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-12">
                <hr>
                <h3>Social Media</h3>
                <div id='schedules'>
                <%= f.fields_for :social_media_authors do |social_media_author| %>
                  <%= render 'social_media_author_fields', :f => social_media_author %>
                <% end %>
                <div class='links my-2'>
                  <%= link_to_add_association 'add Social Media', f, :social_media_authors, class:"btn btn-primary" %>
              </div>
              <hr>
              </div>
            </div>
            </div>

            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :bio, :class => 'control-label' %> <small></small>
                  <%= f.text_area :bio, :class => 'form-control',rows:5 %>
                  <%=f.error_span(:bio) %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="form-group mt-3">
                  <%= f.submit nil, :class => 'btn btn-success' %>
                  <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-light' %>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <% end %>
  </div>
  <div class="col-md-4">

    <%= form_for @user_with_password, :html => { :class => "form-horizontal user" } do |f| %>

    <div class="card">
      <div class="card-body">
        <h3>Change Password</h3>
        <hr>
        <div class="">
          <div class="">
            <div class="form-group">
              <%= f.label :current_password, :class => 'control-label' %>
              <%= f.password_field :current_password, :class => 'form-control',:required => true %>
              <%=f.error_span(:current_password) %>
            </div>
          </div>
          <div class="">
            <%= f.label :password, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password, :class => 'form-control', required:true %>
            <%=f.error_span(:password) %>
          </div>
          <div class="">
            <%= f.label :password_confirmation, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password_confirmation, :class => 'form-control', required:true %>
            <%=f.error_span(:password_confirmation) %>
          </div>
        </div>
        <div class="mt-3">
          <%= f.submit 'Change password', :class => 'btn btn-success' %>
        </div>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/users/_social_media_author_fields.html.erb
<div class="nested-fields mb-3">
  <div class="row">
    <div class="col-5">
      <%= f.text_field :account_username, class: 'form-control', placeholder: "input your username" %>
    </div>
    <div class="col-5">
      <%= f.select :socialmedium_id, Socialmedium.all.map {|s| [s.title, s.id ]},{:include_blank => '-Choose platform-'}, :class=>"form-control w-100 select2 category-select",required: true %>
    </div>
    <div class="col-2">
       <%= link_to_remove_association  f, class:'btn btn-danger' do %>
        <i class="fa fa-minus-circle" aria-hidden="true"></i>
       <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= users_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'formedit' %>
</div>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_index_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-success mb-2', target:'_blank' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:username) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:email) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:role) %></th>
                <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td class="text-center"><%= link_to user.id, user_path(user) %></td>
                <td class="text-center"><%= user.username %></td>
                <td class="text-center"><%= user.email %></td>
                <td class="text-center"><%= user.role %></td>
                <td class="text-center">
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  user_path(user), :class => 'btn btn-info btn-xs', target:'_blank' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_user_path(user), :class => 'btn btn-warning btn-xs', target:'_blank' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  user_path(user),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.table').DataTable();
  } );
</script>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= users_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<section id="latest">
  <div class="container">

    <div class="row">
      <div class="col-md-3">
        <div class="" style="top:70px;z-index:9">
          <div class="mb-3">
            <img src="<%= @user.avatar %>" alt="<%= @user.avatar %>" style="width:170px;border:4px solid #ffbe04;border-radius:50%;margin-bottom:20px;">
          </div>
        </div>
        <a href="<%= user_path(@user.slug) %>">
          <h1 class="username"><%= @user.full_name %></h1>
        </a>
        <div class=" mb-2">
        <p>  <%= @user.bio %> </p>
        </div>
        <div class="d-flex mb-5">
          <% @user.social_media_authors.each do |x| %>
          <div class="mr-3 mt-1">
            <a href="<%= x.socialmedium.link %>/<%= x.account_username %>/" target="_blank" style="font-size:20px"><%= x.socialmedium.icon.html_safe %></a>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-9">
        <ul class="list-article">
          <% @user.articles.publish.each do |x| %>
          <a href="<%= dtl_article_path(x.category.parent.slug ,x.slug) %>">
            <div class="row mb-3">
              <div class="col-md-4">
                <img  src="<%= x.image.url(:medium_short) %>" alt="Generic placeholder image" class="w-100">
              </div>
              <div class="col-md-8">
                <h4 class="mt-0 mb-1 title"><%= x.title %></h4>
                <p>
                  <%= x.metades.truncate(170) %>
                </p>
              </div>
            </div>
          </a>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
</section>