config/routes.rb
Rails.application.routes.draw do
  resources :socialmedia
  resources :category_directories
  resources :contacts
  resources :directories
  get 'dashboard/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'page#index'
  get 'dashboard' => "dashboard#index"
  get '/search' => "page#search", as: :search_path
  get '/dashboard/banner-homepage' => "dashboard#banner_homepage", as: :banner_homepage
  get '/dashboard/banner-category' => "dashboard#banner_category", as: :banner_category
  get '/dashboard/banner-article' => "dashboard#banner_article", as: :banner_article
  get 'backtosetup' => "dashboard#backtosetup"
  get 'backtosetup-event' => "dashboard#backtosetup_event"
  get 'open' => 'page#open', as: :open_article
  get 'contact-us'=> 'page#contact', as: :contact_us

  resources :users
  resources :videos
  resources :events
  resources :articles

  get 'index' => 'page#index', as: :index
  get 'event' => 'page#event', as: :page_event
  get 'all-category' => 'categories#index', as: :all_category
  get 'all-category-article' => 'categories#article', as: :all_category_article
  get 'all-category-event' => 'categories#event', as: :all_category_event
  get 'all-directory' => 'directories#index', as: :all_directory
  get 'semua-artikel' => 'page#latest', as: :latest
  get 'author' => 'page#author', as: :all_author

  resources :categories, path: ''

  devise_for :users,
  path:'admin',
  path_names:{sign_in: 'login',sign_out:'logout'}

  get 'author/:id', to: 'users#show', as: :author
  get ':category_name/:id', to: 'articles#show', as: :dtl_article

end

app/models/category_directory.rb
class CategoryDirectory < ApplicationRecord

  has_many :directories

end

app/controllers/category_directories_controller.rb
class CategoryDirectoriesController < ApplicationController
  before_action :set_category_directory, only: [:show, :edit, :update, :destroy]
  layout 'admin', except: 'show'
  before_action :authenticate_user!
  # GET /category_directories
  # GET /category_directories.json
  def index
    @category_directories = CategoryDirectory.all
  end

  # GET /category_directories/1
  # GET /category_directories/1.json
  def show
  end

  # GET /category_directories/new
  def new
    @category_directory = CategoryDirectory.new
  end

  # GET /category_directories/1/edit
  def edit
  end

  # POST /category_directories
  # POST /category_directories.json
  def create
    @category_directory = CategoryDirectory.new(category_directory_params)

    respond_to do |format|
      if @category_directory.save
        format.html { redirect_to category_directories_url, notice: 'Category directory was successfully created.' }
        format.json { render :show, status: :created, location: @category_directory }
      else
        format.html { render :new }
        format.json { render json: @category_directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_directories/1
  # PATCH/PUT /category_directories/1.json
  def update
    respond_to do |format|
      if @category_directory.update(category_directory_params)
        format.html { redirect_to category_directories_url, notice: 'Category directory was successfully updated.' }
        format.json { render :show, status: :ok, location: @category_directory }
      else
        format.html { render :edit }
        format.json { render json: @category_directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_directories/1
  # DELETE /category_directories/1.json
  def destroy
    @category_directory.destroy
    respond_to do |format|
      format.html { redirect_to category_directories_url, notice: 'Category directory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_directory
      @category_directory = CategoryDirectory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_directory_params
      params.require(:category_directory).permit(:title, :description, :slug)
    end
end

app/helpers/category_directories_helper.rb
module CategoryDirectoriesHelper
end

app/views/category_directories/_form.html.erb
<%= form_for @category_directory, :html => { :class => "form-horizontal category_directory" } do |f| %>

<% if @category_directory.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@category_directory.errors.count, "error") %> prohibited this category_directory from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @category_directory.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="card">
  <div class="card-body">

    <div class="form-group">
      <%= f.label :title, :class => 'control-label' %>
      <%= f.text_field :title, :class => 'form-control' %>
      <%=f.error_span(:title) %>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => 'control-label' %>
      <%= f.text_area :description, :class => 'form-control' %>
      <%=f.error_span(:description) %>
    </div>

    <div class="form-group">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        category_directories_path, :class => 'btn btn-default' %>

    </div>
  </div>
</div>


<% end %>

app/views/category_directories/edit.html.erb
<%- model_class = CategoryDirectory -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/category_directories/index.html.erb
<%- model_class = CategoryDirectory -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_index_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")),new_category_directory_path,:class => 'btn btn-success mb-2', target:'_blank' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th><%= model_class.human_attribute_name(:description) %></th>
                <th><%= model_class.human_attribute_name(:slug) %></th>
                <th><%= model_class.human_attribute_name(:created_at) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @category_directories.each do |category_directory| %>
              <tr>
                <td><%= link_to category_directory.id, category_directory_path(category_directory) %></td>
                <td><%= category_directory.title %></td>
                <td><%= category_directory.description %></td>
                <td><%= category_directory.slug %></td>
                <td><%=l category_directory.created_at %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  category_directory_path(category_directory), :class => 'btn btn-default btn-xs', target:'_blank' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_category_directory_path(category_directory), :class => 'btn btn-default btn-xs', target:'_blank' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  category_directory_path(category_directory),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                  
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.table').DataTable();
  } );
</script>

app/views/category_directories/new.html.erb
<%- model_class = CategoryDirectory -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= articles_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/category_directories/show.html.erb
<%- model_class = CategoryDirectory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @category_directory.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @category_directory.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:slug) %>:</strong></dt>
  <dd><%= @category_directory.slug %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              category_directories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_directory_path(@category_directory), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_directory_path(@category_directory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>