config/routes.rb
Rails.application.routes.draw do
  resources :socialmedia
  resources :category_directories
  resources :contacts
  resources :directories
  get 'dashboard/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'page#index'
  get 'dashboard' => "dashboard#index"
  get '/search' => "page#search", as: :search_path
  get '/dashboard/banner-homepage' => "dashboard#banner_homepage", as: :banner_homepage
  get '/dashboard/banner-category' => "dashboard#banner_category", as: :banner_category
  get '/dashboard/banner-article' => "dashboard#banner_article", as: :banner_article
  get 'backtosetup' => "dashboard#backtosetup"
  get 'backtosetup-event' => "dashboard#backtosetup_event"
  get 'open' => 'page#open', as: :open_article
  get 'contact-us'=> 'page#contact', as: :contact_us

  resources :users
  resources :videos
  resources :events
  resources :articles

  get 'index' => 'page#index', as: :index
  get 'event' => 'page#event', as: :page_event
  get 'all-category' => 'categories#index', as: :all_category
  get 'all-category-article' => 'categories#article', as: :all_category_article
  get 'all-category-event' => 'categories#event', as: :all_category_event
  get 'all-directory' => 'directories#index', as: :all_directory
  get 'semua-artikel' => 'page#latest', as: :latest
  get 'author' => 'page#author', as: :all_author

  resources :categories, path: ''

  devise_for :users,
  path:'admin',
  path_names:{sign_in: 'login',sign_out:'logout'}

  get 'author/:id', to: 'users#show', as: :author
  get ':category_name/:id', to: 'articles#show', as: :dtl_article

end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  has_many :articles
  has_many :events

  has_many :children, :class_name => "Category", :foreign_key => :parent_id
  belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id, optional: true

  class << self
    def main_category
      Category.where(main: true)
    end

    def article_category
       Category.where.not(main: true).where.not(id: Category.event_category)
    end

    def event_category
      Category.where(slug:'event').first.children
    end

    def parent
      Category.where(parent_id: [nil,""])
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'admin', except: 'show'
  before_action :authenticate_user!, except: 'show'
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    if params[:title].present?
     @categories = Category.where("title LIKE ?", "%#{params[:title]}%")
   end

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if params[:category].present?
      @first_five = Article.publish.where(category_id: Category.find(params[:category]).id).order(publish: :desc).order(publish: :desc).limit(5)
      @all_article =  Article.publish.where(category_id: Category.find(params[:category])).where.not(id:  @first_five.map(&:id) ).order(publish: :desc).page(params[:page]).per(4)
    else
      @first_five = Article.publish.where(category_id: @category.children.map(&:id)).order(publish: :desc).limit(5)
      @all_article =  Article.publish.where(category_id: @category.children.map(&:id)).where.not(id:  @first_five.map(&:id) ).order(publish: :desc).page(params[:page]).per(4)
    end

    prepare_meta_tags(
    title: @category.title,
    description: @category.desc,
      twitter: {
      site_name: "BEBAS AJA | #{@category.title || @category.title}" ,
      site: '@bebasajacom',
      creator: '@bebasajacom',
      card: 'summary',
      description:   @category.desc,
      title: @category.title || @category.title,
    },
    og: {
      url: request.protocol + request.host_with_port+"/"+ @category.slug,
      site_name:  "BEBAS AJA | #{@category.title || @category.title}" ,
      title: @category.title || @category.title,
      type: 'category',
      description:  @category.desc
      })
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to all_category_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to all_category_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to all_category_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def article
    @categories = Category.where.not(main: true).where.not(id: Category.event_category)
    if params[:title].present?
      @categories =  @categories.where("title LIKE ?", "%#{params[:title]}%")
    end
  end

  def event
    @categories = Category.event_category
    if params[:title].present?
      @categories =  @categories.where("title LIKE ?", "%#{params[:title]}%")
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title, :desc, :parent_id, :main, :slug, :created_at, :index, :map, :directory_id, :venue)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_articles.html.erb
<% i =  [*0..4].sample %>

<% @all_article.each do |x| %>
<div class="col-md-4 p-10" style="order:<%= i = i + 1 %> ">
  <div class="position-relative">
    <div class="ftr-category">
      <%= x.category.title %>
    </div>
    <img src="<%= x.image.url(:ads_google) %>" alt="" class="w-100">
    <div class="ftr-title">
      <h5><a href="<%= article_path(x.slug) %>"><%= x.title %></a></h5>
    </div>
  </div>
</div>
<% end %>
<div class="col-md-4 p-10" style="order:<%= i = i + 1 %>">
  <div class="position-relative">
    <img src="https://via.placeholder.com/300x250" alt="" class="w-100">
  </div>
</div>
<div class="col-md-4 p-10" style="order:<%= i = i + 1 %>">
  <div class="position-relative">
    <img src="https://via.placeholder.com/300x250" alt="" class="w-100">
  </div>
</div>

app/views/categories/_form.html.erb
<div class="row">
  <% if @category.errors.any? %>
    <div class="col-md-12">
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :title, :class => 'control-label' %>
                <%= f.text_field :title, :class => 'form-control', required:true %>
                <%=f.error_span(:title) %>
              </div>
            </div>
          </div>
          <% unless @category.new_record? %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :slug, :class => 'control-label' %>
                <%= f.text_field :slug, :class => 'form-control', disable:true %>
                <%=f.error_span(:slug) %>
              </div>
            </div>
          </div>
          <% end %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :parent_id, :class => 'control-label' %>
                <%= f.select :parent_id, Category.parent.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2"%>
                <%=f.error_span(:parent_id) %>
              </div>
            </div>

          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :desc, :class => 'control-label' %>
                <%= f.text_area :desc, :class => 'form-control',:ckeditor => {:removePlugins => 'forms,about,flash',:removeButtons => 'Image', :height => '300px'} %>
                <%=f.error_span(:desc) %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col text-center">
              <div class="form-group">
                <%= f.submit nil, :class => 'btn btn-success' %>
                <%= link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-light' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(".select2").select2();
  $("input[type='checkbox'], input[type='radio']").bootstrapSwitch();
</script>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_index_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">

  <div class="accordion" id="accordionExample">
    <% @categories.main_category.each do |x| %>
    <div class="card">
      <div class="card-header bg-dark d-flex align-items-center justify-content-between" id="headingOne">
        <h2 class="mb-0">
          <button class="btn btn-link text-light" type="button" data-toggle="collapse" data-target="#<%= x.slug %>" aria-expanded="true" aria-controls="<%= x.slug %>">
            <%= x.title %>
          </button>
        </h2>
        <div class="d-block">
          <%= link_to 'show',  category_path(x), :class => 'btn btn-default btn-xs', target:'_blank' %>
          <%= link_to 'edit',
          edit_category_path(x), :class => 'btn btn-warning btn-xs', target:'_blank' %>
          <button type="button" name="button" class="btn btn-primary btn-xs" type="button" data-toggle="collapse" data-target="#<%= x.slug %>" aria-expanded="true" aria-controls="<%= x.slug %>">
            <i class="fa fa-caret-down" aria-hidden="true"></i>
          </button>
        </div>
      </div>

      <div id="<%= x.slug %>" class="collapse " aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th class=""><%= model_class.human_attribute_name(:id) %></th>
                <th class=""><%= model_class.human_attribute_name(:title) %></th>
                <th class=""><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% x.children.each do |category| %>
              <tr>
                <td class=""><%= link_to category.id, category_path(category) %></td>
                <td class=""><%= category.title.upcase %></td>
                <td class="">
                  <% if x.slug == "event" %>
                  <a href="event?category=<%= category.slug %>" class="btn btn-default btn-xs", target="_blank">Show</a>
                  <% else %>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  category_path(category), :class => 'btn btn-default btn-xs', target: "blank" %>
                  <% end %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_category_path(category), :class => 'btn btn-warning btn-xs', target:'_blank' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  category_path(category),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% end %>

  </div>

</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.table').DataTable();
  } );
</script>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/show.html.erb
<% if @first_five.first.nil? %>
<section id="category" class="pb-0">
  <div class="container text-center ">
    <h1 class="mb-3">Belum Ada Artikel</h1>
  </div>
  </section>

  <% else %>
  <section id="category" class="pb-0">
    <div class="container">
      <div class="category-title text-center">
        <h1 style="text-transform:uppercase">
          <%= @category.title %>
        </h1>
        <hr>

        <div class="d-flex justify-content-center" style="flex-wrap: wrap;">
          <a href="<%= category_path(@category.slug) %>" class="btn btn-outline-yellow m-1">All</a>
          <% @category.children.each do|x| %>
            <a href="<%= request.original_url %>?&category=<%= x.slug%>" class="btn btn-outline-yellow m-1" style="text-transform: uppercase;"  ><%= x.title %></a>
          <% end %>
        </div>
      </div>
      <div class="row row-custom">
        <div class="col-md-6 p-10">
          <div class="position-relative">
            <div class="ftr-category">
              <%= @first_five.first.category.title %>
            </div>
            <a href="<%= dtl_article_path(@first_five.first.category.parent.slug, @first_five.first.slug) %>" target="_blank">
            <img src="<%= @first_five.first.image.url(:medium_rectangle) %>" alt="" class="w-100">
            </a>
            <div class="ftr-title">
              <h3><a href="<%= dtl_article_path(@first_five.first.category.parent.slug, @first_five.first.slug) %>" target="_blank"><%= @first_five.first.title %></a></h3>
            </div>
          </div>
        </div>
        <div class="col-md-6 p-10">
          <div class="row row-custom">
            <% @first_five.where.not(id: @first_five.first.id).limit(4).each do |x| %>
              <div class="col-md-6 p-10 pt-0">
              <div class="position-relative">
                <div class="ftr-category">
                  <%= x.category.title %>
                </div>
                <a href="<%= dtl_article_path(x.category.parent.slug, x.slug) %>" target="_blank">
                <img src="<%= x.image.url(:category_thumb) %>" alt="" class="w-100">
                </a>
                <div class="ftr-title">
                  <h5><a href="<%= dtl_article_path(x.category.parent.slug, x.slug) %>" target="_blank"><%= x.title %></a></h5>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="mansory" class="pt-0">
    <div class="container" >
      <div class="row row-custom" id="articles">

        <% @all_article.each do |x| %>
        <% i =  [*0..4].sample %>
        <div class="col-md-4 p-10" style="order:<%= i   %> ">
          <div class="position-relative">
            <div class="ftr-category">
              <%= x.category.title %>
            </div>
            <a href="<%= dtl_article_path(x.category.parent.slug, x.slug) %>" target="_blank">
            <img src="<%= x.image.url(:ads_google) %>" alt="" class="w-100">
            </a>
            <div class="ftr-title">
              <h5><a href="<%= dtl_article_path(x.category.parent.slug, x.slug) %>" target="_blank"><%= x.title %></a></h5>
            </div>
          </div>
        </div>
        <% end %>

      <!--  <div class="col-md-4 p-10" style="order:<%#  [*0..4].sample  %>">
          <div class="position-relative">
            <img src="https://via.placeholder.com/300x250" alt="" class="w-100">
          </div>
        </div>
        <div class="col-md-4 p-10" style="order:<%#  [*0..4].sample   %>">
          <div class="position-relative">
            <img src="https://via.placeholder.com/300x250" alt="" class="w-100">
          </div>
        </div>
      </div>  -->
      <div class="text-center">
        <%= paginate @all_article, theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </section>


<% end %>

app/views/categories/show.js.erb
$('#load_more').replaceWith("<%= escape_javascript(link_to_next_page(@all_article, 'Muat Lebih Banyak', :remote => true, :id=>'load_more',class: "btn btn--ghost",param_name: :pg_ns))%>");
$('#articles').append("<%= escape_javascript(render 'categories/articles')%>");